/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.pkgfinal.de.curso;

/**
 *
 * @author User21
 */
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;

public class Menuprinc extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Menuprinc
     */
    public Menuprinc() {
    	
        
        initComponents();
        /*se pasa tamaño de el jframe y string al jpanel
        esto se hará en todos los jframe*/
        Dimension dim = getSize();
        Imagenfondo im = new Imagenfondo(dim);
        im.setImage("/cosa/fondo.png");
        ImageIcon ic = new ImageIcon("src/cosa/insulina.png");
        setTitle("Medinsa");
        this.setIconImage(ic.getImage());
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.add(im,BorderLayout.CENTER);
        
        this.pack();
        
        //tooltip declaration
        
        Insulina.setToolTipText("Introducir o consultar la insulina");
        comida.setToolTipText("Consultar valores calóricos");
        recetas.setToolTipText("Deliciosas recetas recomendadas");
        //end of the tooltip declaration
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comida = new javax.swing.JButton();
        recetas = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        Ayuda = new javax.swing.JButton();
        Insulina = new javax.swing.JButton();
        Crear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        comida.setText("Comidas");
        comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comidaActionPerformed(evt);
            }
        });

        recetas.setText("Recetas");
        recetas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                recetasFocusGained(evt);
            }
        });
        recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recetasActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cosa/titulo.png"))); // NOI18N
        titulo.setText("jLabel1");

        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });

        Insulina.setText("Acceder modo insulina");
        Insulina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsulinaActionPerformed(evt);
            }
        });

        Crear.setText("Crear cuenta");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insulina, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recetas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(Salir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Crear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(comida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(Insulina, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(comida, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recetas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salir)
                    .addComponent(Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recetasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recetasFocusGained
        // TODO add your handling code here:
            
    }//GEN-LAST:event_recetasFocusGained

    private void recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recetasActionPerformed
        // TODO add your handling code here:
        try{
            //se abre el pdf mediante la clase Desktop
            File flrecetas = new File("src/cosa/recetas.pdf");
            Desktop reader;
            reader = Desktop.getDesktop();
            if(reader.isSupported(Desktop.Action.valueOf("OPEN"))){
                reader.open(flrecetas);
                
            }else{
                JOptionPane.showMessageDialog(this,"Error appered: 0002a","Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error appered: 0001a","Error",JOptionPane.ERROR_MESSAGE);
           
            
        }
        
    }//GEN-LAST:event_recetasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
            System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        // TODO add your handling code here:
        Ayuda ay = new Ayuda();
        
    }//GEN-LAST:event_AyudaActionPerformed

    private void comidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comidaActionPerformed
        // TODO add your handling code here:
        try{
            //Se abre mediante la clase Desktop
            File flrecetas = new File("src/cosa/tabla.pdf");
            Desktop reader;
            reader = Desktop.getDesktop();
            if(reader.isSupported(Desktop.Action.valueOf("OPEN"))){
                reader.open(flrecetas);

            }else{
                JOptionPane.showMessageDialog(this,"Error appered: 0002a","Error",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error appered opening the pdf file","Error: 0001a",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_comidaActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        Caccount d= new Caccount(this,true);
    }//GEN-LAST:event_CrearActionPerformed

    private void InsulinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsulinaActionPerformed
        // TODO add your handling code here:
        Login login = new Login(this,true);
    }//GEN-LAST:event_InsulinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuprinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuprinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuprinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuprinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuprinc().setVisible(true);
                
                
            }
        });
    }
    
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Insulina;
    private javax.swing.JButton Salir;
    private javax.swing.JButton comida;
    private javax.swing.JButton recetas;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
    
    
    
}
